spring:
  datasource:
    url: jdbc:mysql://factcheck-mysql:3306/factcheck
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce.pool:
        max-active: 10
        max-idle: 10
        min-idle: 2

jwt:
  secret: ${JWT_SECRET}

chrome:
  client:
    id: ${CHROME_CLIENT_ID}