spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    url: jdbc:mysql://localhost:3306/factcheck?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    user: factcheck
    password: factcheck
  datasource:
    url: jdbc:mysql://localhost:3306/factcheck?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC&rewriteBatchedStatements=true
    username: factcheck
    password: factcheck
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      lettuce.pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
management:
  metrics:
    tags:
      application: ${spring.application.name}
